source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Toggle config flags dynamically
source = ~/.local/state/omarchy/toggles/hypr/*.conf

###################
### KEYBINDINGS ###
###################
$s = SUPER

unbind = $s, SPACE
unbind = $s SHIFT, SPACE

unbind = $s, H
unbind = $s, L
unbind = $s, K
unbind = $s, J

bind = $s, H, movefocus, l
bind = $s, L, movefocus, r
bind = $s, K, movefocus, u
bind = $s, J, movefocus, d

bind = $s, Q, killactive,
bind = $s, V, togglefloating,

bind = $s, R, exec, killall waybar && waybar
bind = $s, T, exec, killall hyprpaper && hyprpaper

bind = $s, RETURN, exec, $terminal
bind = $s SHIFT, B, exec, $browser
bind = $s SHIFT, S, exec, hyprshot -m region --clipboard-only
