splash = false

wallpaper {
	monitor = DP-3
	# path = ~/.config/hypr/bgs/city-bg.jpeg
	path = ~/.config/hypr/bgs/city-balcony1.png
	fit_mode = cover
}

wallpaper {
	monitor = DP-1
	path = ~/.config/hypr/bgs/swirlbg.jpg
	fit_mode = cover
}

wallpaper {
	monitor = DP-2
	path = ~/.config/hypr/bgs/swirlbg.jpg
	fit_mode = cover
}
