format = """$username$hostname:$directory\
( \\[$git_branch( $git_status)\\])$character"""
add_newline = false

[username]
show_always = true
# format = "[$user](bold blue)"
format = "[$user](bold fg:#7aa2f7)"

[hostname]
ssh_only = false
format = "[@$hostname](fg:#6a6fb1)"

[directory]
format = "[$path](fg:#a4aed6)"
truncation_length = 3
truncation_symbol = ""
truncate_to_repo = true

[git_branch]
symbol = ""
format = "[$symbol$branch](fg:#a3be8c)"

[git_status]
format = "[$all_status$ahead_behind](fg:#d8dee9)"
modified = "[!${count}](fg:#ebcb8b)"
staged = "[+${count}](fg:#a3be8c)"
untracked = "[?${count}](fg:#ebcb8b)"
deleted = "[✘${count}](fg:#bf616a)"
renamed = "[»${count}](fg:#ebcb8b)"
stashed = "[$${count}](fg:#88c0d0)"
conflicted = "[=${count}](fg:#bf616a)"
ahead = "[⇡${count}](fg:#88c0d0)"
behind = "[⇣${count}](fg:#88c0d0)"
diverged = "[⇕](fg:#88c0d0)"

[character]
success_symbol = "\n[\\$](bold fg:#a3be8c)"
error_symbol = "\n[\\$](fg:#bf616a)"

########################################
# BARE BASH SHELL WITH NORD COLORS
########################################

# format = """$username@$hostname:$directory\
# ( \\[$git_branch( $git_status)\\])\n$character"""
# add_newline = false
#
# [username]
# show_always = true
# # format = "[$user](bold blue)"
# format = "[$user](bold fg:#81a1c1)"
#
# [hostname]
# ssh_only = false
# format = "[$hostname](fg:#81a1c1)"
#
# [directory]
# format = "[$path](fg:#81a1c1)"
# truncation_length = 8
# truncation_symbol = ""
#
# [git_branch]
# symbol = ""
# format = "[$symbol$branch](fg:#a3be8c)"
#
# [git_status]
# format = "[$all_status$ahead_behind](fg:#d8dee9)"
# modified = "[!${count}](fg:#ebcb8b)"
# staged = "[+${count}](fg:#a3be8c)"
# untracked = "[?${count}](fg:#ebcb8b)"
# deleted = "[✘${count}](fg:#bf616a)"
# renamed = "[»${count}](fg:#ebcb8b)"
# stashed = "[$${count}](fg:#88c0d0)"
# conflicted = "[=${count}](fg:#bf616a)"
# ahead = "[⇡${count}](fg:#88c0d0)"
# behind = "[⇣${count}](fg:#88c0d0)"
# diverged = "[⇕](fg:#88c0d0)"
#
# [character]
# success_symbol = "[\\$](bold fg:#a3be8c)"
# error_symbol = "[\\$](fg:#bf616a)"


###########################################
# POWERLINE-STYLE CUSTOM COLORS (NORD-ish)
###########################################

# "$schema" = 'https://starship.rs/config-schema.json'
#
# add_newline = false
#
# format = """
# $os$username\
# [](fg:#2e3440 bg:#3d4252)\
# $directory\
# [](fg:#3d4252 bg:#4c566a)\
# $git_branch\
# $git_status\
# [](fg:#4c566a)\
# \n$character"""
#
# [time]
# disabled = true
# time_format = "[%d] %R "
# format = '[$time](fg:#434c5e bg:#212733)'
#
# [os]
# disabled = false
#
# [os.symbols]
# Arch = "[  ](fg:#81a1c1 bg:#2e3440)"
# Debian = "[  ](fg:#81a1c1 bg:#2e3440)"
# CentOS = " "
# Linux = " "
# Raspbian = "[  ](fg:#81a1c1 bg:#2e3440)"
# Ubuntu = " "
#
# [username]
# disabled = false
# show_always = true
# format = '[$user ](fg:#81a1c1 bg:#2e3440)'
#
# [directory]
# format = "[ $path ](fg:#d8dee9 bg:#3d4252)"
# truncation_length = 2
# truncation_symbol = "…/"
# truncate_to_repo = true
#
# [git_branch]
# symbol = ""
# format = '[ $symbol $branch ](fg:#a3be8c bg:#4c566a)'
#
# [git_status]
# format = '([ $all_status$ahead_behind ](bg:#4c566a))'
#
# # unique status formatters
# modified = "[!${count}](fg:#ebcb8b bg:#4c566a)"
# staged = "[+${count}](fg:#a3be8c bg:#4c566a)"
# untracked = "[?${count}](fg:#ebcb8b bg:#4c566a)"
# deleted = "[✘${count}](fg:#bf616a bg:#4c566a)"
# renamed = "[»${count}](fg:#ebcb8b bg:#4c566a)"
# stashed = "[$${count}](fg:#88c0d0 bg:#4c566a)"
# conflicted = "[=${count}](fg:#bf616a bg:#4c566a)"
# ahead = "[⇡${count}](fg:#88c0d0 bg:#4c566a)"
# behind = "[⇣${count}](fg:#88c0d0 bg:#4c566a)"
# diverged = "[⇕](fg:#88c0d0 bg:#4c566a)"
#
# [character]
# success_symbol = "[❯](bold #a3be8c)"
# error_symbol = "[❯](bold #bf616a)"
